# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 567095e51e72e1a73bc8d1492469f2a05b406d533a17570a5dd2e98aac4d5121d9f9ff5a56e76ef77ea7d4a28b35a31566c5208cb44c890a5b4c067d1be57500

test:
  secret_key_base: 350462a3c2ad031ede042d7d665c5628975cfd688d3ede5508e935f41877f9ad0013e6e8f5410b3f00b416b13d5e759035cfa6aef33bb2c104d25b3215b1e07a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
